import "./globals.css";
import { Poppins } from "next/font/google";
import Header from "@/components/layout/Header";
import HomeMapSelection from "@/components/layout/HomeMapSelection";
import Menu from "@/components/layout/Menu";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <HomeMapSelection/>
        <Menu/>
        {children}
      </body>
    </html>
  );
}
